---
version: "3.4"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB={{cookiecutter.project_slug}}
    ports:
      - "5432:5432"